name: Build and Publish

# on:
#   release:
#     types: [published]
#   workflow_dispatch:
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write  
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # ubuntu-latest  → Linux x86_64 (+ aarch64 via QEMU)
        # windows-latest → Windows x86_64
        # macos-latest   → macOS arm64  (Apple Silicon runner)
        # macos-13       → macOS x86_64  NOT SUPPORTED!

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU (Linux aarch64)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4
        env:
          CIBW_BUILD: "cp312-* cp313-* cp314-*"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: "native"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_BEFORE_BUILD: "pip install cmake ninja"
          CIBW_TEST_COMMAND: "pytest {project}/test/game/ -x -q"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_TEST_SKIP: "*-manylinux_aarch64 *-musllinux_aarch64"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false
      - run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  # pypi-publish:
  #   name: Build and publish Python 🐍 distributions to PyPI
  #   needs: [build_wheels, build_sdist] # Waits for builds to finish
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - name: Download all wheel artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         pattern: wheels-* # Grabs wheels-ubuntu-latest, wheels-macos-latest, etc.
  #         path: dist/
  #         merge-multiple: true

  #     - name: Download sdist artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: sdist
  #         path: dist/

  #     - name: Publish distribution 📦 to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         # We don't need a password/token input because we use 
  #         # Trusted Publishing (id-token permission above).
  #         print-hash: true
